apiVersion: v1
kind: Service
metadata:
  name: {{ include "turbineproxy.fullname" . }}
  labels:
    {{- include "turbineproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: proxy
      port: {{ .Values.service.proxyPort }}
      targetPort: proxy
      protocol: TCP
    - name: dashboard
      port: {{ .Values.service.dashboardPort }}
      targetPort: dashboard
      protocol: TCP
  selector:
    {{- include "turbineproxy.selectorLabels" . | nindent 4 }}
